name: .NET Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          - "01-Moq-CustomerComm"
          - "02-NUnit-Calculator-Basics"
          - "03-NUnit-Calculator-Parameterized"
          - "04-NUnit-UtilLib-HostNameParser"
          - "05-NUnit-AccountsManagerLib"
          - "06-NUnit-CollectionsLib"
          - "07-NUnit-FourSeasonsLib-TestCaseSource"
          - "08-NUnit-LeapYearCalculatorLib"
          - "09-NUnit-UserManagerLib"
          - "10-NUnit-Moq-ConverterLib"

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        working-directory: ${{ matrix.project }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ matrix.project }}
        run: dotnet build --no-restore --configuration Release

      - name: Test
        working-directory: ${{ matrix.project }}
        run: dotnet test --no-build --configuration Release --verbosity normal
